// <auto-generated />
namespace ServerTeste2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usuarioadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuarioadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201509241655544_usuarioadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
